# Generated by Django 5.2.5 on 2025-09-03 02:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bouncer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="admitted_count",
        ),
        migrations.RemoveField(
            model_name="game",
            name="rejected_count",
        ),
    ]
