# Generated by Django 5.2.5 on 2025-09-03 02:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bouncer", "0003_alter_game_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="player_id",
        ),
    ]
