# Generated by Django 5.2.5 on 2025-09-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bouncer", "0004_remove_game_player_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="completion_reason",
            field=models.TextField(
                blank=True, help_text="Reason for completion or failure", null=True
            ),
        ),
    ]
