# Generated by Django 5.2.5 on 2025-09-03 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouncer', '0005_game_completion_reason'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGame',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bouncer.game')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('bouncer.game',),
        ),
        migrations.CreateModel(
            name='RemoteGame',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bouncer.game')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('bouncer.game',),
        ),
        migrations.AddField(
            model_name='game',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
