# Generated by Django 5.2.5 on 2025-09-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouncer', '0007_game_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('error', 'Error')], default='running', max_length=20),
        ),
    ]
